### ISSUE TITLE
Move src/portmatching/pyo3.rs to pyrs

### ISSUE THREAD

**Issue by lmondada** [CQCL/tket2#148]
There is no reason this should live within `tket2`.

**Comment by aborgna-q** [comment]
Half of the code there is implementing `#[pymethods]` for structs in the crate. Those cannot be moved out (otherwise we'd be doing foreign type impls).

The other half of the code defines `PyPatternMatch`, which is used by the aforementioned impls so we cannot move out without changing the API.

I'll close this as WONTDO. We can review it in the future if we want to refactor the API in a way that doesn't require those impls.

**Comment by aborgna-q** [comment]
Reopening this as it's useful for #178
