### ISSUE TITLE
Prototype a "lazify-measurement" hugr->hugr pass

### ISSUE THREAD

**Issue by doug-q** [CQCL/tket2#432]
The h-series runtime wants to be lazy in using the results of measurements, to facilitate runtime pipelining.

I suggest we can achieve this with the following:
* create a `lazy` extension with
  * A custom type `Lazy<T>`
  * An operation `lift<T>: T -> Lazy<T>`
  * An operation `read<T>: Lazy<T> -> T`
* create a "quantum.tket2.lazy" extension with
  * A custom operation `measure: Qubit -> (Qubit, Lazy<BOOL_T>)` 
*  Create a hugr-> hugr pass that
  * replaces all "quantum.tket2.measure" operations with "quantum.tket2.lazy.measure" operations.
  * For all users of the `BOOL_T` result of "quantum.tket2.measure":
    *  For `Conditional` control input, output-of-`DataflowBlock` control input, output-of-`TailLoop` control input, indirect call, call to public function, or custom op input: `read` the Lazy<BOOL_T> .
    * Otherwise modify the op to take a a `Lazy<BOOL_T>` and iterate
Note that here a public function is either a `FuncDecl` or a function which is the target of `LoadFunction`

I intend to start with the `Lazy<T>` type being linear, and adding `dup` and `free` functions. I anticipate that lowerings will want to manage waitable "handles". `dup` will lower to "increment reference count" and `free` will lower to "decrement reference count". If making it linear ends up being too hard I will switch to non-linear to get something working. 

This code should live in `tket2-hseries`

- [x] #472
- [x] #473
- [x] #474
- [x] #491
- [x] #492

**Comment by acl-cqc** [comment]
The need for `dup` here is critical. If we didn't need to `dup` then we could take `Lazy<BOOL_T>` as `QUBIT` and `read` thereof as `measure`....

if (given) we do need `dup` then these `Lazy`s have basically (exactly??) the same interface as `Ptr`s i.e. https://github.com/CQCL-DEV/hugrverse/issues/21 right?

**Comment by acl-cqc** [comment]
> They are not exactly the same as `Ptr`s, they have no `write` op.

Ah, yes, true. The writing is captured in the closure of how to compute the value.

And (importantly) this closure, even tho referred to by the non-linear/`dup`-able Lazy, can capture the linear QUBIT because it can only be called once.

Agreed Lazy/Future is a useful general thing to have. Is it any easier if we do something Qubit/measure-specific? I'm not sure it is (==> this is "develop `Future` extension", dependent on the `Ptr` extension - I think this Future effectively wraps some version of `Ptr<Sum<QUBIT | Bool>>`)
